name: Build Windows Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cx_Freeze

    - name: Build executable
      run: |
        cd SafeSync
        python setup.py build

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: executable
        path: SafeSync/build/exe.win-amd64-3.9/  # Adjust this path based on your setup.py configuration
