name: Build Executable

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cx_Freeze
          pip install paramiko
          pip install scp
      - name: Verify Tkinter Installation
        run: python -c "import tkinter; print('Tkinter is installed')"

      
      - name: Build executable
        run: python SafeSync/setup.py build

      - name: List build directory
        run: ls -R build/

      - name: Run the built executable
        run: |
          cd build/exe.win-amd64-3.10  # Adjust the path based on your build output
          ./SafeSync.exe > output.log 2>&1 # Replace with the actual name of your executable
        continue-on-error: true  # Continue even if this step fails

      - name: Upload executable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-executable
          path: build/
